version: '3.8'

services:
  app-dev:
    container_name: bots-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db  
    networks:
      - app-network

  app-test:
    container_name: bots-api-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=test
      - DB_HOST=db-test
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=test_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - app-network
    command: npm run test

  db: 
    image: postgres:17-alpine
    container_name: bots-api-db
    env_file:
      - .env  
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  db-test:
    image: postgres:17-alpine
    container_name: bots-api-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    volumes:
      - db-test-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  db-test-data:
